name: recsys_env
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pip
  - pip:
    - torch-scatter~=2.1.0
    - torch-sparse~=0.6.16
    - torch-cluster~=1.6.0
    - torch-spline-conv~=1.2.1
    - torch-geometric==2.2.0
